/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as long as the process is up. Used by Kubernetes
         *     liveness probes and Docker healthchecks. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Polls the database driver with a 2s timeout. Used by
         *     Kubernetes readiness probes. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
                /** @description Database unreachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verbose health check
         * @description Per-subsystem status: database, registered plugins, optional
         *     syncer cluster view.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok" | "degraded";
                            subsystems?: {
                                [key: string]: string;
                            };
                            plugins?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text-format exposition. Backed by the
         *     `prometheus.Registry` constructed at startup. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled authentication backends and public tenants
         * @description Returns the names of registered authentication providers, with
         *     the configured `general.default_auth_backend` first, plus the
         *     list of active tenants whose `listed` flag is true (or absent).
         *     The `login_key` is never included here.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backend list and public tenant list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                backends?: {
                                    /** @example microsoft */
                                    name: string;
                                    /** @enum {string} */
                                    kind: "password" | "redirect";
                                    /** @example Microsoft 365 */
                                    display_name?: string;
                                    /** @example microsoft */
                                    icon?: string;
                                }[];
                                /** @description Active tenants with listed:true (or absent). Sorted
                                 *     by display_name. Empty array when there is only the
                                 *     default tenant or none are listed.
                                 *      */
                                tenants?: {
                                    /** @description Tenant slug. */
                                    id: string;
                                    /** @description Human-readable label. */
                                    display_name: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve an opaque per-tenant login key
         * @description Resolves a per-tenant `login_key` to the tenant's `id` and
         *     `display_name`. Returns a generic 404 for an empty, unknown, or
         *     suspended tenant — it never resolves by slug, so it cannot be
         *     used to enumerate tenants. Used by the login page when the URL
         *     carries `?key=<login_key>`.
         *
         */
        get: {
            parameters: {
                query: {
                    /** @description The opaque per-tenant login key. */
                    key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant identity for the given key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description Tenant slug. */
                                id: string;
                                /** @description Human-readable label. */
                                display_name: string;
                            };
                        };
                    };
                };
                /** @description Key not found, empty, or tenant suspended. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin an OIDC redirect login
         * @description Initiates an OAuth 2.0 / OIDC authorization-code flow for the named
         *     provider (e.g. `microsoft`). Sets a short-lived signed state cookie
         *     and issues a 302 redirect to the identity provider's authorize endpoint.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description Relative SPA path to return to after sign-in. If omitted, the SPA lands on /web/alerts. */
                    return_to?: string;
                    /** @description Tenant slug. Omit to use the default tenant. */
                    org?: string;
                };
                header?: never;
                path: {
                    /** @description The configured `method` value (e.g. `microsoft`). */
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the identity provider's authorize endpoint. Sets a short-lived signed state cookie. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC redirect callback
         * @description Receives the authorization-code callback from the identity provider.
         *     Exchanges the code for tokens, validates the ID token, resolves or
         *     creates the Snooze user, and issues a signed session JWT.
         *
         *     On success, redirects to `/web/login/callback#token=<jwt>`.
         *     On failure, redirects to `/web/login?sso_error=<message>`.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description Authorization code returned by the identity provider. */
                    code?: string;
                    /** @description CSRF state token. Must match the signed state cookie. */
                    state?: string;
                    /** @description Error code returned by the identity provider on failure. */
                    error?: string;
                };
                header?: never;
                path: {
                    /** @description The configured `method` value (e.g. `microsoft`). */
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description On success, redirect to /web/login/callback with the session token in the URL fragment. On failure, redirect to /web/login?sso_error=... */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local user login (bcrypt-hashed password) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/ldap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LDAP login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description LDAP bind / search failed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
                /** @description Backend disabled. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anonymous login
         * @description Issues a bearer JWT with the `anonymous` method, used when
         *     `general.anonymous_enabled: true`. No request body.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Anonymous bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Anonymous backend not registered. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new access+refresh pair
         * @description Validates the supplied refresh token, revokes it, and issues a
         *     fresh access token alongside a rotated refresh token. The caller
         *     must replace its stored pair with the new one — the previous
         *     refresh token is no longer valid. An invalid, expired, revoked
         *     or unknown token returns 401 with a generic message.
         *
         *     Roles and permissions are re-resolved on every refresh so an
         *     admin's revocation of a permission takes effect within the
         *     access-token lease (default 1 hour).
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New access + refresh pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid, expired, revoked or unknown refresh token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Best-effort revocation of the supplied refresh token. Unknown or
         *     already-revoked tokens are treated as no-ops — the endpoint
         *     always returns 204 so a client cleaning up state never sees a
         *     500. The access token (Bearer JWT) is not revoked: it continues
         *     to be valid until its own expiry. Clients should drop both
         *     tokens client-side after calling this endpoint.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Logout acknowledged (idempotent). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-service password change
         * @description Replaces the authenticated user's password. Only available when
         *     the caller's JWT `method` claim is `local` — LDAP / anonymous
         *     accounts are managed by their backing provider.
         *
         *     The caller MUST supply their current password; the server
         *     re-runs the bcrypt comparison through the same code path as
         *     `/api/v1/login/local`, so the failure mode (and timing) is
         *     identical to a bad-credentials login.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The caller's current password. */
                        current_password: string;
                        /** @description The new password (bcrypt-hashed server-side). */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Password updated. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing claims or wrong current password. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
                /** @description Caller's auth method is not `local`; self-service password
                 *     change is not available for that backend.
                 *      */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
                /** @description Empty body field(s). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/apikeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my API keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's API keys (secrets stripped). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["APIKey"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an API key for myself
         * @description Mints a key scoped to the caller, carrying a subset of the caller's own permissions. The raw key is returned once. Not permitted when the request is itself authenticated with an API key.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["APIKeyCreate"];
                };
            };
            responses: {
                /** @description Created. Body includes the raw `key` (shown once). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIKeyCreated"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                /** @description Invalid expiry, or requested permissions are malformed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/apikeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of my API keys */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test notification for an action config
         * @description Delivers a single synthetic alert through the notifier named by
         *     `selected`, using `subcontent` as its action_form configuration. The
         *     config does NOT need to be persisted first — this powers the
         *     "Send test" button in the Actions editor. The notifier's real Send
         *     path runs, so a 200 proves end-to-end delivery (URL, auth, payload).
         *     No record is mutated.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Notifier plugin registry key (teams, slack, webhook, …). */
                        selected: string;
                        /** @description The action_form values for that notifier. */
                        subcontent?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Test notification delivered. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                /** @description Unknown plugin. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
                /** @description Plugin is not a notifier, or upstream delivery failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one or many alert records
         * @description Accepts a single record object or an array of records. Each
         *     record is run through the configured `core.process_plugins`
         *     pipeline; the response includes the post-pipeline records and
         *     any per-record processing errors.
         *
         *     **Multi-tenant routing** — in a multi-tenant deployment, supply
         *     `Authorization: Bearer <ingest_token>` (the per-tenant opaque token
         *     from `GET /api/v1/tenant/{id}`) to route ingestion to a specific
         *     tenant. When no token is present or the token is unknown, the request
         *     falls back to the `default` tenant. Single-tenant deployments need no
         *     token (existing behaviour preserved).
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Record"] | components["schemas"]["Record"][];
                };
            };
            responses: {
                /** @description Per-record processing result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Record"][];
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cluster/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster + plugin status
         * @description Cluster member list (graded ok/degraded/down from the `nodes`
         *     heartbeat collection; leader = alphabetically-first ok member — Snooze
         *     has no real leader election) plus the loaded-plugin roster. Falls back
         *     to a synthetic `standalone` member on a single-node deploy. Backs the
         *     admin Status page.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster status snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cluster?: {
                                members?: {
                                    name?: string;
                                    /** @enum {string} */
                                    status?: "ok" | "degraded" | "down";
                                }[];
                                leader?: string;
                            };
                            plugins?: {
                                name?: string;
                                loaded?: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condition/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a search-bar query string into a Condition AST
         * @description Always returns 200 (even on a query parse error) so the SearchBar can
         *     render an inline marker. A 400 is returned only when the JSON envelope
         *     itself is malformed. Exactly one of `condition` / `error` is set.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        query: string;
                    };
                };
            };
            responses: {
                /** @description Parse result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            condition?: {
                                [key: string]: unknown;
                            };
                            error?: {
                                pos?: number;
                                token?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condition/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field catalog for SearchBar autocomplete */
        get: {
            parameters: {
                query?: {
                    collection?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Field catalog (empty array for unknown collections). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                name?: string;
                                type?: string;
                                description?: string;
                                values?: string[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snooze/{uid}/retro_apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay a stored snooze against existing records
         * @description Applies the snooze's condition to the `record` collection: deletes
         *     matches when `discard` is true, otherwise tags them `snoozed:<name>`.
         *     Requires the `rw_record` permission.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retro-apply counts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            matched: number;
                            deleted?: number;
                            tagged?: number;
                            snooze: string;
                        };
                    };
                };
                /** @description Snooze not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants
         * @description Returns all tenant records. Requires `ro_tenant` or `rw_tenant`.
         *     Evaluated against platform scope, not any individual tenant.
         *
         */
        get: {
            parameters: {
                query?: {
                    offset?: number;
                    limit?: number;
                    orderby?: string;
                    asc?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Tenant"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create tenant
         * @description Creates a new organization and seeds its default roles (`admin`,
         *     `viewer`, `notifications`). Requires `rw_tenant`. The `id` slug must be
         *     unique and must not be `default`. If `ingest_token` is omitted a random
         *     token is generated and returned in the response — this is the only
         *     opportunity to retrieve it.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantCreateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{id}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure/reset a tenant's local admin password
         * @description Provisions or resets the local admin for the given tenant. If the
         *     user identified by `username` (default "admin") already exists its
         *     password is rotated; otherwise a new local user is created with the
         *     `admin` role. Requires `rw_tenant`. The returned `password` is shown
         *     exactly once — store it immediately.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tenant slug. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Admin username to provision or reset (default "admin"). */
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description Admin credential (password shown once). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCredential"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{id}/rotate-login-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a tenant's login key
         * @description Generates a fresh opaque `login_key` for the tenant, invalidating
         *     any previously shared login links. Also bootstraps a key for tenants
         *     that were created before this feature was introduced. Requires
         *     `rw_tenant`. The new key is returned in the response — update any
         *     shared login links immediately.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tenant slug. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New login key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Tenant slug. */
                            id: string;
                            /** @description Freshly generated opaque login key. */
                            login_key: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tenant by id
         * @description Requires `ro_tenant` or `rw_tenant`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete tenant
         * @description Requires `rw_tenant`. The reserved "default" tenant cannot be deleted
         *     (server returns 409).
         *
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update tenant display_name / status / ingest_token / listed
         * @description Requires `rw_tenant`. `id` is immutable.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/webhook/{webhook}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inbound webhook receiver
         * @description Convert a foreign monitoring source's alert payload into one or
         *     more Snooze records and submit them to the pipeline. The
         *     payload schema is source-specific; see each integration's
         *     documentation for the wire format.
         *
         *     Receivers are unauthenticated by default. When `ingest.token` is
         *     configured every request must carry it as
         *     `Authorization: Bearer <token>` or `?token=<token>`.
         *
         *     **Multi-tenant routing** — supply a per-tenant `ingest_token` (from
         *     `GET /api/v1/tenant/{id}`) to route webhook payloads to a specific
         *     tenant. Falls back to `default` when absent or unknown. The global
         *     `ingest.token` guard (if configured) is evaluated first.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    webhook: "alertmanager" | "azuremonitor" | "cloudwatch" | "datadog" | "grafana" | "influxdb2" | "kapacitor" | "newrelic" | "prometheus" | "sentry";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Records accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Record"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat ping (dead-man's-switch)
         * @description Keep a heartbeat alive: stamps the named heartbeat's `last_seen`
         *     to now. Public, but each ping must present the heartbeat's
         *     server-generated per-record token (a configured `ingest.token`
         *     applies on top). `GET` is also accepted.
         *
         */
        post: {
            parameters: {
                query: {
                    /** @description The heartbeat name. */
                    name: string;
                    /** @description The heartbeat's server-generated secret token. */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Heartbeat stamped. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No heartbeat with that name. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every permission string contributed by plugins
         * @description Returns the sorted union of `metadata.provides` from every
         *     registered plugin, plus the canonical `rw_all` / `ro_all`
         *     wildcards and a per-plugin `{rw,ro}_<name>` pair.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Permission list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/{plugin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the JSON Schema attached to a DataModel plugin */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON Schema document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Plugin has no schema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered plugin's metadata
         * @description Returns the parsed `metadata.yaml` of every registered plugin
         *     (name / display_name / icon / action_form / widgets / etc.).
         *     The React frontend uses this to render plugin-defined typed
         *     forms — e.g. the Action sub-types (Mail, Webhook, Patlite) —
         *     instead of free-form JSON textareas.
         *
         *     Plugins are sorted by name so the payload is deterministic.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plugin metadata list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Metadata"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/{plugin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single plugin's metadata */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plugin metadata. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Metadata"];
                        };
                    };
                };
                /** @description Plugin not registered. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard aggregate statistics
         * @description Returns time-series counters, per-dimension totals, a live record
         *     snapshot and a weekday distribution for the requested time window.
         *     `from` and `to` are RFC3339 timestamps (or Unix epoch seconds);
         *     `bucket` is the series resolution in seconds (default 3600).
         *
         */
        get: {
            parameters: {
                query: {
                    /** @description Window start — RFC3339 or Unix epoch seconds. */
                    from: string;
                    /** @description Window end — RFC3339 or Unix epoch seconds. */
                    to: string;
                    /** @description Series bucket size in seconds. */
                    bucket?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated statistics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResponse"];
                    };
                };
                /** @description Bad `from` or `to` parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin / collection name. The built-in set is enumerated in
                 *     `internal/pluginimpl/all/all.go`.
                 *
                 *     The `apikey` collection is the tenant-scoped admin surface over user
                 *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                 *     `POST`/`PUT` are rejected here — mint keys via
                 *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                 *     (`name`/`expires_at`), revoke, or `DELETE`.
                 *      */
                plugin: components["parameters"]["PluginPath"];
            };
            cookie?: never;
        };
        /**
         * List documents in a plugin's collection
         * @description The `q` query parameter is a base64url-encoded JSON condition.
         *     Default sort is by insertion order; pass `orderby` + `asc` to
         *     change it.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description Base64url-encoded JSON condition. Empty (or absent) selects
                     *     every document. Use `POST /{plugin}/search` for queries that
                     *     won't fit in a URL.
                     *      */
                    q?: components["parameters"]["QueryQ"];
                    offset?: components["parameters"]["Offset"];
                    limit?: components["parameters"]["Limit"];
                    orderby?: components["parameters"]["OrderBy"];
                    asc?: components["parameters"]["Asc"];
                };
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
                /** @description Malformed query. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Create one or many documents */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | {
                        [key: string]: unknown;
                    }[];
                };
            };
            responses: {
                /** @description Created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
                /** @description Schema validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        /** Delete every document matching the query */
        delete: {
            parameters: {
                query?: {
                    /** @description Base64url-encoded JSON condition. Empty (or absent) selects
                     *     every document. Use `POST /{plugin}/search` for queries that
                     *     won't fit in a URL.
                     *      */
                    q?: components["parameters"]["QueryQ"];
                };
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deletion summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                deleted?: number;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search with a JSON body (avoids URL-length limits) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        condition?: {
                            [key: string]: unknown;
                        };
                        /** @default 0 */
                        offset?: number;
                        /** @default 20 */
                        limit?: number;
                        orderby?: string;
                        /** @default true */
                        asc?: boolean;
                    };
                };
            };
            responses: {
                /** @description Paginated list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin / collection name. The built-in set is enumerated in
                 *     `internal/pluginimpl/all/all.go`.
                 *
                 *     The `apikey` collection is the tenant-scoped admin surface over user
                 *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                 *     `POST`/`PUT` are rejected here — mint keys via
                 *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                 *     (`name`/`expires_at`), revoke, or `DELETE`.
                 *      */
                plugin: components["parameters"]["PluginPath"];
                uid: string;
            };
            cookie?: never;
        };
        /** Fetch a single document by UID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        /** Replace a document */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Replaced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a single document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Partial update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *
                     *     The `apikey` collection is the tenant-scoped admin surface over user
                     *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
                     *     `POST`/`PUT` are rejected here — mint keys via
                     *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
                     *     (`name`/`expires_at`), revoke, or `DELETE`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIKey: {
            uid?: string;
            owner?: string;
            owner_method?: string;
            name?: string;
            /** @description First 12 chars of the key, for identification. */
            key_prefix?: string;
            permissions?: string[];
            groups?: string[];
            created_at?: number;
            expires_at?: number;
            revoked_at?: number;
        };
        APIKeyCreate: {
            name: string;
            /** @description Must be a subset of the caller's own permissions. */
            permissions?: string[];
            /**
             * Format: date-time
             * @description RFC3339. Omit to default to the configured maximum lifetime.
             */
            expires_at?: string;
        };
        APIKeyCreated: components["schemas"]["APIKey"] & {
            /** @description The raw key (snz_…). Returned ONCE, on creation only. */
            key?: string;
        };
        /** @example {
         *       "status": "ok"
         *     } */
        StatusOK: {
            /** @enum {string} */
            status: "ok";
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
            /** @description Optional tenant slug. Omitted or empty defaults to "default".
             *     Pass when the server hosts multiple organizations and the user
             *     wants to log in to a specific one (D10).
             *      */
            org?: string;
        };
        LoginResponse: {
            /** @description HS256 JWT access token. Send as `Authorization: Bearer <token>`. */
            token: string;
            /**
             * Format: date-time
             * @description Absolute expiry of the access token.
             */
            expires_at: string;
            /** @description Opaque refresh token. Present on initial login and on every
             *     `/api/v1/login/refresh` response. Store securely on the client;
             *     POST it to `/api/v1/login/refresh` to mint a new access token
             *     and POST it to `/api/v1/login/logout` to revoke the session.
             *     Each refresh rotates the token — the previous value is revoked
             *     server-side and a new one is returned.
             *      */
            refresh_token?: string;
            /**
             * Format: date-time
             * @description Absolute expiry of the refresh token.
             */
            refresh_expires_at?: string;
            /** @enum {string} */
            method: "local" | "ldap" | "anonymous";
            /** @description Tenant slug the token is scoped to. Mirrors the `tenant_id` JWT
             *     claim. Empty on legacy tokens — treated as `default` by the server.
             *      */
            tenant_id?: string;
        };
        RefreshRequest: {
            /** @description The refresh token returned by a prior login or refresh. */
            refresh_token: string;
        };
        /** @description One organization (tenant). id is the immutable URL/login-safe slug
         *     stamped as tenant_id on every scoped document. display_name is mutable.
         *      */
        Tenant: {
            /** @description Immutable slug, used as tenant_id on all scoped documents. */
            id: string;
            /** @description Human-readable label; mutable. */
            display_name: string;
            /**
             * @description 'suspended' blocks login + ingest but retains data.
             * @enum {string}
             */
            status: "active" | "suspended";
            /** @description Per-tenant ingest token for unauthenticated ingress (D4). */
            ingest_token?: string;
            /**
             * @description Controls whether this tenant appears in the public login list
             *     returned by GET /api/v1/login. Default true. Set to false for
             *     SaaS tenants reached only via their per-tenant login_key link.
             *
             * @default true
             */
            listed: boolean;
            /** @description Opaque, rotatable per-tenant discovery secret. Share
             *     /web/login?key=<login_key> to let users reach this tenant's login
             *     page without exposing the tenant list. Never included in the public
             *     login index. Rotate via POST /api/v1/tenant/{id}/rotate-login-key.
             *      */
            login_key?: string;
            /** Format: int64 */
            created_at?: number;
            /** Format: int64 */
            updated_at?: number;
        };
        /** @description The canonical alert document moving through the Snooze
         *     pipeline. Mirrors `pkg/snoozetypes.Record`. Fields are
         *     permissive — plugins routinely inject extra keys that don't
         *     appear in this schema.
         *      */
        Record: {
            uid?: string;
            host?: string;
            source?: string;
            process?: string;
            severity?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            /** Format: int64 */
            date_epoch?: number;
            /** Format: int64 */
            ttl?: number;
            environment?: string;
            tags?: string[];
            raw?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            state?: "" | "open" | "ack" | "close" | "shelved";
            plugins?: string[];
        } & {
            [key: string]: unknown;
        };
        ListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ListMeta"];
        };
        ListMeta: {
            count: number;
            limit: number;
            offset: number;
            total: number;
        };
        ErrEnvelope: {
            error: components["schemas"]["ErrBody"];
        };
        ErrBody: {
            /** @enum {string} */
            code: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation_error" | "unavailable" | "internal";
            message: string;
            details?: {
                [key: string]: unknown;
            };
            request_id?: string;
        };
        /** @description Parsed `metadata.yaml` for a registered plugin. Mirrors
         *     `plugins.Metadata` in Go. Field keys are snake_case (JSON tags
         *     align with the YAML keys so the frontend reads the document
         *     verbatim).
         *      */
        Metadata: {
            /** @description Registry key (machine-readable identifier; matches `Plugin.Name()`
             *     on the server). Injected by the metadata HTTP handler — stable
             *     across plugins regardless of what their YAML `name:` field carries.
             *     Use this (not `name`) to match a notification action's `action.selected`.
             *      */
            plugin_name: string;
            /** @description Display label taken from the plugin's YAML `name:` field (e.g. "Send email", "Run a script"). Use `plugin_name` for machine matching. */
            name: string;
            /** @description Human-readable label (YAML `desc`). */
            display_name?: string;
            /** @description Icon glyph name. */
            icon?: string;
            default_sorting?: string;
            default_ordering?: string;
            auto_reload?: boolean;
            /** @description Free-form per-plugin widget descriptors. */
            widgets?: {
                [key: string]: unknown;
            };
            /** @description Per-field form descriptor keyed by field name. */
            action_form?: {
                [key: string]: components["schemas"]["FormField"];
            };
            /** @description Typed catalogue of runtime settings (settings plugin only). Same
             *     FormField shape as `action_form`; the optional `group` field on
             *     each entry lets the frontend render the picker grouped by section.
             *      */
            setting_form?: {
                [key: string]: components["schemas"]["FormField"];
            };
            /** @description Permission strings the plugin contributes. */
            provides?: string[];
            /** @description Per-route overrides, keyed by route path. */
            routes?: {
                [key: string]: {
                    class_name?: string;
                    check_permissions?: boolean;
                    primary_key?: string[];
                    duplicate_policy?: string;
                    authentication?: boolean;
                };
            };
            options?: {
                [key: string]: unknown;
            };
            search_fields?: string[];
            audit?: boolean;
            force_order?: number;
            tree?: boolean;
        } & {
            [key: string]: unknown;
        };
        /** @description One field of a plugin's `action_form`. The React frontend renders
         *     a typed input based on `component`; `options` populates choice
         *     widgets (Selector, Radio).
         *      */
        FormField: {
            display_name?: string;
            /** @description Widget kind (e.g. String, Number, Text, Selector, Radio, Password). */
            component?: string;
            description?: string;
            required?: boolean;
            default_value?: unknown;
            /** @description Logical section the field belongs to (e.g. "general" or
             *     "notification" for settings). Used by the frontend to render
             *     grouped pickers; ignored by the server.
             *      */
            group?: string;
            options?: {
                text?: string;
                value?: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        StatsResponse: {
            data: components["schemas"]["StatsData"];
            meta: components["schemas"]["StatsMeta"];
        };
        StatsData: {
            series: components["schemas"]["SeriesBucket"][];
            totals: components["schemas"]["StatsTotals"];
            snapshot: components["schemas"]["StatsSnapshot"];
            /** @description Alert counts keyed by weekday ("0" = Sunday … "6" = Saturday). */
            weekday: {
                [key: string]: number;
            };
        };
        SeriesBucket: {
            /**
             * Format: date-time
             * @description Bucket start timestamp (RFC3339).
             */
            t: string;
            /** @description Per-series alert counts for this bucket. */
            counts: {
                [key: string]: number;
            };
        };
        StatsTotals: {
            by_severity: {
                [key: string]: number;
            };
            by_environment: {
                [key: string]: number;
            };
            /** @description Top-10 hosts by alert count. */
            by_host: {
                [key: string]: number;
            };
            by_action_success: {
                [key: string]: number;
            };
            by_action_failure: {
                [key: string]: number;
            };
            by_throttled: {
                [key: string]: number;
            };
            by_snoozed: {
                [key: string]: number;
            };
            by_notification: {
                [key: string]: number;
            };
        };
        StatsSnapshot: {
            /** @description Alert counts keyed by state string. */
            by_state: {
                [key: string]: number;
            };
            /** @description Total alert hits in the requested window. */
            total_hits: number;
            /** @description Count of records currently in the open state. */
            open: number;
            /** @description Count of records currently in the ack state. */
            ack: number;
            /** @description Count of records currently in the close state. */
            closed: number;
        };
        StatsMeta: {
            /**
             * Format: date-time
             * @description Actual window start used by the server (RFC3339).
             */
            from: string;
            /**
             * Format: date-time
             * @description Actual window end used by the server (RFC3339).
             */
            to: string;
            /** @description Series bucket size in seconds. */
            bucket: number;
        };
        /** @description Provisioned local-admin credential. The `password` is shown exactly
         *     once (it is not stored in plaintext); save it immediately.
         *      */
        AdminCredential: {
            /** @description Login username of the provisioned admin. */
            username: string;
            /** @description Plaintext password shown once. Store it securely. */
            password: string;
            /** @description Authentication method used (always 'local' for provisioned admins). */
            method: string;
            /** @description True if the user was newly created; false if the password was reset on an existing user. */
            created: boolean;
        };
        /** @description Response body for POST /api/v1/tenant. */
        TenantCreateResponse: {
            /** @description List of created tenant id(s). */
            added: string[];
            /** @description Present only when a first admin was provisioned (create_admin was not false). */
            admin?: components["schemas"]["AdminCredential"];
        };
        /** @description Request body for POST /api/v1/tenant. */
        TenantCreate: {
            /** @description Immutable slug. Must be unique. Reserved value `default` is rejected. */
            id: string;
            /** @description Human-readable label. */
            display_name: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "suspended";
            /**
             * @description Whether the tenant appears in the public login page's tenant list.
             *     Set false for SaaS-style deployments where tenants reach their login
             *     page via their opaque login link instead.
             *
             * @default true
             */
            listed: boolean;
            /** @description Per-tenant ingest token. If omitted the server generates a random
             *     24-byte hex token and returns it in the response body. Store it:
             *     this is the only time the plaintext is returned.
             *      */
            ingest_token?: string;
            /** @description Provision a first local admin (default true). Set false for LDAP/SSO-only tenants. */
            create_admin?: boolean;
            /** @description Username for the first admin (default "admin"). */
            admin_username?: string;
        };
        /** @description Request body for PATCH /api/v1/tenant/{id}. All fields optional. */
        TenantUpdate: {
            /** @description New human-readable label. */
            display_name?: string;
            /**
             * @description Change the lifecycle state.
             * @enum {string}
             */
            status?: "active" | "suspended";
            /** @description Rotate the ingest token. Supply a new value or an empty string to
             *     disable unauthenticated ingestion for this tenant. The server does
             *     NOT auto-generate a new token on update — supply one explicitly.
             *      */
            ingest_token?: string;
            /** @description Toggle public visibility in the login tenant list. Set to false
             *     to hide the tenant from the public login dropdown; share the
             *     per-tenant login_key link instead.
             *      */
            listed?: boolean;
        };
    };
    responses: {
        /** @description Malformed request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrEnvelope"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrEnvelope"];
            };
        };
        /** @description Authenticated but lacking the required permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrEnvelope"];
            };
        };
        /** @description Conflict (e.g. attempt to delete a reserved resource). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Plugin / collection name. The built-in set is enumerated in
         *     `internal/pluginimpl/all/all.go`.
         *
         *     The `apikey` collection is the tenant-scoped admin surface over user
         *     API keys: reads require `ro_apikey` and writes require `rw_apikey`.
         *     `POST`/`PUT` are rejected here — mint keys via
         *     `POST /api/v1/user/me/apikeys`; admins may only `PATCH`
         *     (`name`/`expires_at`), revoke, or `DELETE`.
         *      */
        PluginPath: "action" | "aggregaterule" | "alertmanager" | "apikey" | "audit" | "azuremonitor" | "cloudwatch" | "comment" | "datadog" | "discord" | "environment" | "googlechat" | "grafana" | "heartbeat" | "influxdb2" | "kapacitor" | "kv" | "mail" | "newrelic" | "notification" | "ntfy" | "opsgenie" | "pagerduty" | "patlite" | "profile" | "prometheus" | "pushover" | "record" | "role" | "rule" | "script" | "sentry" | "servicenow" | "settings" | "slack" | "snooze" | "sns" | "stats" | "statuspage" | "telegram" | "twilio" | "user" | "webhook" | "widget";
        /** @description Base64url-encoded JSON condition. Empty (or absent) selects
         *     every document. Use `POST /{plugin}/search` for queries that
         *     won't fit in a URL.
         *      */
        QueryQ: string;
        Offset: number;
        Limit: number;
        OrderBy: string;
        Asc: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
