/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as long as the process is up. Used by Kubernetes
         *     liveness probes and Docker healthchecks. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Polls the database driver with a 2s timeout. Used by
         *     Kubernetes readiness probes. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
                /** @description Database unreachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verbose health check
         * @description Per-subsystem status: database, registered plugins, optional
         *     syncer cluster view.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok" | "degraded";
                            subsystems?: {
                                [key: string]: string;
                            };
                            plugins?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Prometheus text-format exposition. Backed by the
         *     `prometheus.Registry` constructed at startup. Always public.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled authentication backends
         * @description Returns the names of registered authentication providers, with
         *     the configured `general.default_auth_backend` first.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backend list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                backends?: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local user login (bcrypt-hashed password) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/ldap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LDAP login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description LDAP bind / search failed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
                /** @description Backend disabled. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anonymous login
         * @description Issues a bearer JWT with the `anonymous` method, used when
         *     `general.anonymous_enabled: true`. No request body.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Anonymous bearer JWT. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Anonymous backend not registered. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one or many alert records
         * @description Accepts a single record object or an array of records. Each
         *     record is run through the configured `core.process_plugins`
         *     pipeline; the response includes the post-pipeline records and
         *     any per-record processing errors.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Record"] | components["schemas"]["Record"][];
                };
            };
            responses: {
                /** @description Per-record processing result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Record"][];
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/{webhook}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inbound webhook receiver
         * @description Convert a foreign monitoring source's alert payload into one or
         *     more Snooze records and submit them to the pipeline. The
         *     payload schema is source-specific; see each integration's
         *     documentation for the wire format.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    webhook: "alertmanager" | "grafana" | "influxdb2" | "kapacitor" | "prometheus";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Records accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Record"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every permission string contributed by plugins
         * @description Returns the sorted union of `metadata.provides` from every
         *     registered plugin, plus the canonical `rw_all` / `ro_all`
         *     wildcards and a per-plugin `{rw,ro}_<name>` pair.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Permission list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/{plugin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the JSON Schema attached to a DataModel plugin */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON Schema document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Plugin has no schema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin / collection name. The built-in set is enumerated in
                 *     `internal/pluginimpl/all/all.go`.
                 *      */
                plugin: components["parameters"]["PluginPath"];
            };
            cookie?: never;
        };
        /**
         * List documents in a plugin's collection
         * @description The `q` query parameter is a base64url-encoded JSON condition.
         *     Default sort is by insertion order; pass `orderby` + `asc` to
         *     change it.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description Base64url-encoded JSON condition. Empty (or absent) selects
                     *     every document. Use `POST /{plugin}/search` for queries that
                     *     won't fit in a URL.
                     *      */
                    q?: components["parameters"]["QueryQ"];
                    offset?: components["parameters"]["Offset"];
                    limit?: components["parameters"]["Limit"];
                    orderby?: components["parameters"]["OrderBy"];
                    asc?: components["parameters"]["Asc"];
                };
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
                /** @description Malformed query. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Create one or many documents */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | {
                        [key: string]: unknown;
                    }[];
                };
            };
            responses: {
                /** @description Created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
                /** @description Schema validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        /** Delete every document matching the query */
        delete: {
            parameters: {
                query?: {
                    /** @description Base64url-encoded JSON condition. Empty (or absent) selects
                     *     every document. Use `POST /{plugin}/search` for queries that
                     *     won't fit in a URL.
                     *      */
                    q?: components["parameters"]["QueryQ"];
                };
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deletion summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                deleted?: number;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search with a JSON body (avoids URL-length limits) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        condition?: {
                            [key: string]: unknown;
                        };
                        /** @default 0 */
                        offset?: number;
                        /** @default 20 */
                        limit?: number;
                        orderby?: string;
                        /** @default true */
                        asc?: boolean;
                    };
                };
            };
            responses: {
                /** @description Paginated list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{plugin}/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin / collection name. The built-in set is enumerated in
                 *     `internal/pluginimpl/all/all.go`.
                 *      */
                plugin: components["parameters"]["PluginPath"];
                uid: string;
            };
            cookie?: never;
        };
        /** Fetch a single document by UID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrEnvelope"];
                    };
                };
            };
        };
        /** Replace a document */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Replaced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a single document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusOK"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Partial update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin / collection name. The built-in set is enumerated in
                     *     `internal/pluginimpl/all/all.go`.
                     *      */
                    plugin: components["parameters"]["PluginPath"];
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "status": "ok"
         *     } */
        StatusOK: {
            /** @enum {string} */
            status: "ok";
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description HS256 JWT. Send as `Authorization: Bearer <token>`. */
            token: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            method: "local" | "ldap" | "anonymous";
        };
        /** @description The canonical alert document moving through the Snooze
         *     pipeline. Mirrors `pkg/snoozetypes.Record`. Fields are
         *     permissive — plugins routinely inject extra keys that don't
         *     appear in this schema.
         *      */
        Record: {
            uid?: string;
            host?: string;
            source?: string;
            process?: string;
            severity?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            /** Format: int64 */
            date_epoch?: number;
            /** Format: int64 */
            ttl?: number;
            environment?: string;
            tags?: string[];
            raw?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            state?: "" | "open" | "ack" | "close" | "shelved";
            plugins?: string[];
        } & {
            [key: string]: unknown;
        };
        ListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ListMeta"];
        };
        ListMeta: {
            count: number;
            limit: number;
            offset: number;
            total: number;
        };
        ErrEnvelope: {
            error: components["schemas"]["ErrBody"];
        };
        ErrBody: {
            /** @enum {string} */
            code: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation_error" | "unavailable" | "internal";
            message: string;
            details?: {
                [key: string]: unknown;
            };
            request_id?: string;
            trace_id?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Plugin / collection name. The built-in set is enumerated in
         *     `internal/pluginimpl/all/all.go`.
         *      */
        PluginPath: "action" | "aggregaterule" | "alertmanager" | "audit" | "comment" | "environment" | "grafana" | "influxdb2" | "kapacitor" | "kv" | "mail" | "notification" | "patlite" | "profile" | "prometheus" | "record" | "role" | "rule" | "script" | "settings" | "snooze" | "stats" | "user" | "webhook" | "widget";
        /** @description Base64url-encoded JSON condition. Empty (or absent) selects
         *     every document. Use `POST /{plugin}/search` for queries that
         *     won't fit in a URL.
         *      */
        QueryQ: string;
        Offset: number;
        Limit: number;
        OrderBy: string;
        Asc: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
