import { useQuery, type UseQueryResult } from "@tanstack/react-query";
import { api, type ApiError } from "@/lib/api/client";
import { defineResource, type ListResponse } from "@/lib/api/resource";
import { encodeConditionQ } from "@/lib/condition/serialize";

export type Comment = {
  uid?: string;
  record_uid: string;
  type: "comment" | "ack" | "close" | "open" | "esc" | "shelve" | "unshelve" | "assign" | "release";
  message?: string;
  date_epoch?: number;
  user?: string;
  /** Auth method of the author — or the chat-ops channel (teams/jira/mcp)
   *  that relayed it, which is why avatars look people up by login first. */
  method?: string;
  /** type=="assign": the login the alert was handed to, and its method. */
  assignee?: string;
  assignee_method?: string;
  /** Shelve window in seconds, echoed back from the posted comment. Only
   * meaningful on type=="shelve", where the server stamps
   * record.shelve_until = now + duration (absent/0 → housekeeping.shelve_timeout). */
  duration?: number;
  /** auto: true when this comment was generated by the housekeeper or aggregaterule plugin.
   * Auto-comments are attributed as "System (auto)" in the timeline and cannot be edited or deleted.
   * The OpenAPI schema does not yet describe this field; it is read defensively. */
  auto?: boolean;
};

export const Comments = defineResource<Comment>("comment");

export type RecordCommentsPage = {
  limit?: number;
  offset?: number;
};

export function useRecordComments(
  record_uid: string | undefined,
  page: RecordCommentsPage = {},
): UseQueryResult<ListResponse<Comment>, ApiError> {
  const q = record_uid
    ? encodeConditionQ({ type: "EQUALS", field: "record_uid", value: record_uid })
    : undefined;
  const limit = page.limit ?? 5;
  const offset = page.offset ?? 0;
  return useQuery<ListResponse<Comment>, ApiError>({
    queryKey: ["comment", "for-record", record_uid ?? "", limit, offset],
    queryFn: ({ signal }) =>
      api<ListResponse<Comment>>("GET", "/comment", {
        query: {
          ...(q !== undefined ? { q } : {}),
          orderby: "date_epoch",
          // Reverse-chronological: newest comments first, so the most recent
          // activity lands on page 1 instead of the last page.
          asc: false,
          limit,
          offset,
        },
        signal,
      }),
    enabled: !!record_uid,
  });
}
