import { useQuery, type UseQueryResult } from "@tanstack/react-query";
import { api, type ApiError } from "@/lib/api/client";
import { defineResource, type ListResponse } from "@/lib/api/resource";
import { encodeConditionQ } from "@/lib/condition/serialize";

export type Comment = {
  uid?: string;
  record_uid: string;
  type: "comment" | "ack" | "close" | "open" | "esc" | "shelve" | "unshelve" | "assign" | "release";
  message?: string;
  date_epoch?: number;
  user?: string;
  /** Auth method of the author — or the chat-ops channel (teams/jira/mcp)
   *  that relayed it, which is why avatars look people up by login first. */
  method?: string;
  /** type=="assign": the login the alert was handed to, and its method. */
  assignee?: string;
  assignee_method?: string;
  /** Shelve window in seconds, echoed back from the posted comment. Only
   * meaningful on type=="shelve", where the server stamps
   * record.shelve_until = now + duration (absent/0 → housekeeping.shelve_timeout). */
  duration?: number;
  /** auto: true when this comment was generated by the housekeeper or aggregaterule plugin.
   * Auto-comments are attributed as "System (auto)" in the timeline and cannot be edited or deleted.
   * The OpenAPI schema does not yet describe this field; it is read defensively. */
  auto?: boolean;
};

export const Comments = defineResource<Comment>("comment");

export type RecordCommentsPage = {
  limit?: number;
  offset?: number;
};

export function useRecordComments(
  record_uid: string | undefined,
  page: RecordCommentsPage = {},
): UseQueryResult<ListResponse<Comment>, ApiError> {
  const q = record_uid
    ? encodeConditionQ({ type: "EQUALS", field: "record_uid", value: record_uid })
    : undefined;
  const limit = page.limit ?? 5;
  const offset = page.offset ?? 0;
  return useQuery<ListResponse<Comment>, ApiError>({
    queryKey: ["comment", "for-record", record_uid ?? "", limit, offset],
    queryFn: ({ signal }) =>
      api<ListResponse<Comment>>("GET", "/comment", {
        query: {
          ...(q !== undefined ? { q } : {}),
          orderby: "date_epoch",
          // Reverse-chronological: newest comments first, so the most recent
          // activity lands on page 1 instead of the last page.
          asc: false,
          limit,
          offset,
        },
        signal,
      }),
    enabled: !!record_uid,
  });
}

/**
 * One folded run of the timeline (GET /comment/runs): consecutive automatic
 * comments of the same type and message — the "New escalation" an alert
 * re-notifying every quarter of an hour writes each time. Anything a person
 * wrote is a run of one. `latest` is the newest member, rendered as the run.
 */
export type CommentRun = {
  key: string;
  count: number;
  first_epoch: number;
  last_epoch: number;
  interval_s: number;
  latest: Comment;
  truncated: boolean;
};

export type CommentRunsResponse = {
  data: CommentRun[];
  meta: { total: number; comments: number; truncated: boolean };
};

/**
 * useRecordCommentRuns pages over a record's timeline with automatic repeats
 * folded (see CommentRun). The fold spans the whole timeline, so it is the
 * server's — internal/api/routes_runs.go. Keyed under "comment" so posting,
 * editing or deleting a comment refreshes it with everything else.
 */
export function useRecordCommentRuns(
  record_uid: string | undefined,
  page: RecordCommentsPage = {},
): UseQueryResult<CommentRunsResponse, ApiError> {
  const limit = page.limit ?? 5;
  const offset = page.offset ?? 0;
  return useQuery<CommentRunsResponse, ApiError>({
    queryKey: ["comment", "runs", record_uid ?? "", limit, offset],
    queryFn: ({ signal }) =>
      api<CommentRunsResponse>("GET", "/comment/runs", {
        query: { record_uid: record_uid ?? "", limit, offset },
        signal,
      }),
    enabled: !!record_uid,
    placeholderData: (prev, prevQuery) =>
      prevQuery?.queryKey?.[2] === (record_uid ?? "") ? prev : undefined,
  });
}

/**
 * useCommentsBetween lists one record's comments inside [from, to], newest
 * first — the members of an expanded run.
 */
export function useCommentsBetween(
  record_uid: string,
  range: { from: number; to: number },
  limit: number,
): UseQueryResult<ListResponse<Comment>, ApiError> {
  const q = encodeConditionQ({
    type: "AND",
    args: [
      { type: "EQUALS", field: "record_uid", value: record_uid },
      { type: "GE", field: "date_epoch", value: range.from },
      { type: "LE", field: "date_epoch", value: range.to },
    ],
  });
  return useQuery<ListResponse<Comment>, ApiError>({
    queryKey: ["comment", "between", record_uid, range.from, range.to, limit],
    queryFn: ({ signal }) =>
      api<ListResponse<Comment>>("GET", "/comment", {
        query: { q, orderby: "date_epoch", asc: false, limit, offset: 0 },
        signal,
      }),
    placeholderData: (prev) => prev,
  });
}
