---
version: '3'

vars:
  GC_NAME: snooze-googlechat

tasks:
  lint:
    cmds:
    - ruff check

  build:
    desc: Build the python package snooze-googlechat
    cmds:
    - uv build

  docker:develop:
    desc: Build the docker image and upload it to a local registry
    cmds:
    - docker build . -t {{ .REPO }}/{{ .GC_NAME }}:develop -v ${PWD}/../client:/client --no-cache
    - docker push {{ .REPO }}/{{ .GC_NAME  }}:develop
    preconditions:
    - sh: docker login "{{ .REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .REPO }}`"

  docker:release:
    desc: Release to GHCR
    deps:
    - cacert
    cmds:
    - docker build . -t {{ .REPO }}/{{ .GC_NAME }}:{{ .VERSION }}
    - docker push {{ .REPO }}/{{ .GC_NAME  }}:{{ .VERSION }}
    preconditions:
    - sh: docker login "{{ .REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .REPO }}`"
