{{- if eq .Values.database.kind "mongo" -}}
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/secretgenerator.mittwald.de/stringsecret_v1alpha1.json
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: "{{ .Release.Name }}-mongodb-credentials"
spec:
  fields:
  - encoding: hex
    fieldName: password
    length: "64"
{{- end }}
