package auth

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"time"

	"golang.org/x/crypto/bcrypt"

	"github.com/snoozeweb/snooze/internal/db"
)

// RootUsername is the canonical bootstrap administrator account.
const RootUsername = "root"

// BootstrapPasswordBytes is the size of the random secret generated by
// EnsureRoot. 24 raw bytes encode to 32 base64 chars — long enough to be
// genuinely unguessable and short enough to copy from a terminal.
const BootstrapPasswordBytes = 24

// EnsureRoot creates a bcrypt-hashed “root“ user with a random password if no
// user exists in the local user collection. The plaintext password is returned
// on first boot so the caller can print it to stderr once; subsequent boots
// return ("", nil). Any unexpected DB error is wrapped with %w.
func EnsureRoot(ctx context.Context, driver db.Driver) (string, error) {
	if driver == nil {
		return "", errors.New("bootstrap: nil db driver")
	}

	// Detect first boot: a missing root document is the trigger. We use
	// GetOne on the canonical filter rather than ListCollections to avoid
	// per-backend differences in collection enumeration.
	existing, err := driver.GetOne(ctx, LocalCollection, db.Document{
		"name":   RootUsername,
		"method": LocalMethod,
	})
	if err == nil && existing != nil {
		// Already provisioned.
		return "", nil
	}

	// Generate a fresh password.
	password, err := generatePassword(BootstrapPasswordBytes)
	if err != nil {
		return "", fmt.Errorf("bootstrap: generate password: %w", err)
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("bootstrap: hash password: %w", err)
	}

	now := time.Now().UTC().Format(time.RFC3339)
	doc := db.Document{
		"name":       RootUsername,
		"method":     LocalMethod,
		"enabled":    true,
		"password":   string(hash),
		"roles":      []string{"admin"},
		"groups":     []string{},
		"created_at": now,
	}

	if _, err := driver.Write(ctx, LocalCollection, []db.Document{doc}, db.WriteOptions{
		Primary:    []string{"name", "method"},
		UpdateTime: true,
	}); err != nil {
		return "", fmt.Errorf("bootstrap: write root user: %w", err)
	}
	return password, nil
}

// generatePassword returns a base64url-encoded random secret of the given raw
// byte length. base64url is used because the rendered string lives on
// terminals and the URL-safe alphabet avoids problems with copy/paste through
// shells and URL bars.
func generatePassword(rawBytes int) (string, error) {
	if rawBytes <= 0 {
		return "", errors.New("password byte length must be positive")
	}
	buf := make([]byte, rawBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}
