export default [
    {
      component: 'CNavItem',
      name: 'Alerts',
      to: '/record',
      fontIcon: 'la la-file-text',
      permissions: ['ro_record', 'rw_record'],
    },
    {
      component: 'CNavItem',
      name: 'Dashboard',
      to: '/dashboard',
      fontIcon: 'la la-tachometer-alt',
      permissions: ['ro_stats', 'rw_stats'],
    },
    {
      component: 'CNavItem',
      name: 'Status',
      to: '/status',
      fontIcon: 'la la-signal',
    },
    {
      component: 'CNavTitle',
      name: 'Core',
    },
    {
      component: 'CNavItem',
      name: 'Rules',
      to: '/rule',
      fontIcon: 'la la-balance-scale',
      permissions: ['ro_rule', 'rw_rule'],
    },
    {
      component: 'CNavItem',
      name: 'Aggregate Rules',
      to: '/aggregaterule',
      fontIcon: 'la la-suitcase',
      permissions: ['ro_aggregaterule', 'rw_aggregaterule'],
    },
    {
      component: 'CNavItem',
      name: 'Snooze',
      to: '/snooze',
      fontIcon: 'la la-bell-slash',
      permissions: ['ro_snooze', 'rw_snooze'],
    },
    {
      component: 'CNavItem',
      name: 'Notifications',
      to: '/notification',
      fontIcon: 'la la-bullhorn',
      permissions: ['ro_notification', 'rw_notification'],
    },
    {
      component: 'CNavTitle',
      name: 'Utils',
    },
    {
      component: 'CNavItem',
      name: 'Actions',
      to: '/action',
      fontIcon: 'la la-code',
      permissions: ['ro_action', 'rw_action'],
    },
    {
      component: "CNavItem",
      name: "Widgets",
      to: '/widget',
      fontIcon: 'la la-plug',
      permissions: ['ro_widget', 'rw_widget']
    },
    {
      component: 'CNavItem',
      name: 'Key-values',
      to: '/kv',
      fontIcon: 'la la-book',
      permissions: ['ro_kv', 'rw_kv'],
    },
    {
      component: 'CNavTitle',
      name: 'Customize',
    },
    {
      component: 'CNavItem',
      name: 'Users',
      to: '/user',
      fontIcon: 'la la-users',
      permissions: ['ro_user', 'rw_user'],
    },
    {
      component: 'CNavItem',
      name: 'Roles',
      to: '/role',
      fontIcon: 'la la-user-friends',
      permissions: ['ro_role', 'rw_role'],
    },
    {
      component: 'CNavItem',
      name: 'Environments',
      to: '/environment',
      fontIcon: 'la la-layer-group',
      permissions: ['ro_environment', 'rw_environment'],
    },
    {
      component: 'CNavItem',
      name: 'Settings',
      to: '/settings',
      fontIcon: 'la la-cog',
      permissions: ['ro_settings', 'rw_settings'],
    },
    {
      component: 'CNavItem',
      name: 'Profile',
      to: '/profile',
      fontIcon: 'la la-sliders',
    },
]
