import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the folder structure under content/.
// Ordering is driven by each page's `sidebar_position` front matter and
// the `position` in each folder's _category_.json. See the conversion notes
// in CHANGELOG / AGENTS.md for how the old Sphinx toctree order was preserved.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
