---
tabs:
    -
        title: 'Actions'
        filter: []
fields:
    -
        label: Name
        key: name
        sortable: true
        thStyle: {width: '20%'}
        tdClass: ['align-middle']
    -
        label: Action
        key: pprint
        thStyle: {width: '50%'}
        tdClass: ['align-middle', 'multiline']
    -
        label: Comment
        key: comment
        thStyle: {width: '30%'}
        tdClass: ['align-middle']
        type: array
    -
        label: ''
        key: button
        sortable: false
        tdClass: ['align-middle', 'text-center']
        thClass: 'text-center'
form:
    name:
        display_name: Name
        component: String
        description: 'Name of the notification entry'
        required: true
    action:
        display_name: Action
        component: APIElement
        endpoint: action/plugin
        primary: action_name
        required: true
        form: action_form
    comment:
        display_name: Comment
        component: Text
